BEGIN;

ALTER TABLE tamagotchis
  ADD COLUMN IF NOT EXISTS background TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS animation  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS position   TEXT NOT NULL DEFAULT '';

COMMIT;