module.exports = {
  apps: [
    {
      name: "p-ink-backend",
      script: "/opt/p-ink/backend/bin/server",
      cwd: "/opt/p-ink/backend",
      restart_delay: 3000,
      max_restarts: 10,
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 10000,
      out_file: "/var/log/p-ink/backend.log",
      error_file: "/var/log/p-ink/backend.error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "p-ink-frontend",
      script: "npm",
      args: "start",
      cwd: "/opt/p-ink/frontend",
      restart_delay: 3000,
      max_restarts: 10,
      kill_timeout: 15000,
      out_file: "/var/log/p-ink/frontend.log",
      error_file: "/var/log/p-ink/frontend.error.log",
      merge_logs: true,
      time: true,
    },
  ],
};